language: node_js

node_js:
  - 0.10
  - 0.11

before_install:
  - npm install -g gulp

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "node test/server.js 2>&1 &"

script:
  - gulp test